# should appear in rotopic list
# Note there's no "". If name doesn't match, you will see controller_manager couldn't be found error
# Also, don't forget to generate urdf
# If there're still errors, reboot the machine. Some services might be messed up
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
joint_1_controller:
  type: effort_controllers/JointPositionController
  joint: link1_bracket_1
  pid: {p: 100.0, i: 0.01, d: 10.0}


joint_2_controller:
  type: effort_controllers/JointPositionController
  joint: link_2_bracket_2_1
  pid: {p: 1000.0, i: 0.01, d: 0.0}

joint_3_controller:
  type: effort_controllers/JointPositionController
  joint: bracket_2_2_link_3
  pid: {p: 1200.0, i: 0.01, d: 0.0}

joint_4_controller:
  type: effort_controllers/JointPositionController
  joint: bracket_3_2_link_4
  pid: {p: 600.0, i: 0.01, d: 10.0}

joint_5_controller:
  type: effort_controllers/JointPositionController
  joint: link_5_link_6
  pid: {p: 1000.0, i: 0.01, d: 10.0}

joint_6_controller:
  type: effort_controllers/JointPositionController
  joint: link_6_left_gripper
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint_7_controller:
  type: effort_controllers/JointPositionController
  joint: link_6_right_gripper
  pid: {p: 100.0, i: 0.01, d: 10.0}
