rjje_arm:
  kinematics_solver_attempts: 1000
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 10
  position_only_ik: True

  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  max_cache_size: 10000
  min_pose_distance: 1
  min_joint_config_distance: 4

  ## For Reference - Considered: 
  ## 1
  # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  ## 2
  # Install TracIK: sudo apt-get install ros-noetic-trac-ik-kinematics-plugin
  # Not chosen because this doesn't allow approx IK
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # solve_type: Distance
  # position_only_ik: False
  # kinematics_solver_timeout: 0.01